#!/usr/bin/env bash

. "$(dirname $0)/megautils.conf"

if mountpoint -q "${unionfs_mnt}"; then
	echo "union filesystem already mounted."
else
	echo "mounting union filesystem..."
	"${unionfs_bin}" -o cow -o allow_other -o uid="${ownerid}" -o gid="${groupid}" "${local_dir}=RW:${megafuse_base}=RO" "${unionfs_mnt}"
	if [ $? ]; then
		echo "union filesystem mounted successfully."
	else
		echo "error mounting union filesystem."
		exit 1
	fi
fi

exit 0
